/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fractionalCollectionSol from "./FractionalCollection.sol";
export type { fractionalCollectionSol };
export type { Lock } from "./Lock";
