"""fractional_listings creator_id + price + expires

Revision ID: 11b59f7832e2
Revises: 16ec637514f0
Create Date: 2025-06-16 15:02:58.930318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b59f7832e2'
down_revision: Union[str, None] = '16ec637514f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fractional_listings', sa.Column('creator_id', sa.String(length=64), nullable=False))
    op.drop_constraint('fractional_listings_creator_fkey', 'fractional_listings', type_='foreignkey')
    op.create_foreign_key(None, 'fractional_listings', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fractional_listings', 'creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fractional_listings', sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fractional_listings', type_='foreignkey')
    op.create_foreign_key('fractional_listings_creator_fkey', 'fractional_listings', 'users', ['creator'], ['id'], ondelete='CASCADE')
    op.drop_column('fractional_listings', 'creator_id')
    # ### end Alembic commands ###
