"""fractional_listings add creator & round_price

Revision ID: 16ec637514f0
Revises: e77a4bfa7130
Create Date: 2025-06-16 14:45:18.585735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ec637514f0'
down_revision: Union[str, None] = 'e77a4bfa7130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fractional_listings', sa.Column('round_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('fractional_listings', sa.Column('creator', sa.String(length=64), nullable=False))
    op.add_column('fractional_listings', sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '7 days'"), nullable=False))
    op.alter_column('fractional_listings', 'token_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('fractional_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('fractional_listings_creator_id_fkey', 'fractional_listings', type_='foreignkey')
    op.create_foreign_key(None, 'fractional_listings', 'users', ['creator'], ['id'], ondelete='CASCADE')
    op.drop_column('fractional_listings', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fractional_listings', sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fractional_listings', type_='foreignkey')
    op.create_foreign_key('fractional_listings_creator_id_fkey', 'fractional_listings', 'users', ['creator_id'], ['id'])
    op.alter_column('fractional_listings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fractional_listings', 'token_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('fractional_listings', 'expires_at')
    op.drop_column('fractional_listings', 'creator')
    op.drop_column('fractional_listings', 'round_price')
    # ### end Alembic commands ###
