"""connect fractional_listings to users

Revision ID: 6ebe85599dc6
Revises: e15ca7c95a57
Create Date: 2025-06-08 15:57:33.359765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebe85599dc6'
down_revision: Union[str, None] = 'e15ca7c95a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fractional_listings', sa.Column('vault_salt', sa.String(), nullable=True))
    op.alter_column('fractional_listings', 'vault',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fractional_listings', 'vault',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('fractional_listings', 'vault_salt')
    # ### end Alembic commands ###
