"""Add_user_verification_and_seed_roles

Revision ID: d84597c29117
Revises: 63a7b0d07729
Create Date: 2025-06-03 19:24:53.213094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84597c29117'
down_revision: Union[str, None] = '63a7b0d07729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_verification',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('didit_session_id', sa.String(), nullable=True),
    sa.Column('id_verified_at', sa.DateTime(), nullable=True),
    sa.Column('aml_status', sa.String(length=16), nullable=True),
    sa.Column('aml_score', sa.SmallInteger(), nullable=True),
    sa.Column('aml_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


    # ⬇️ Add the four KYC-related roles - manually added to seed the roles table
    from sqlalchemy import table, column, String

    role_table = table(
        "roles",
        column("slug", String),
        column("description", String),
    )

    op.bulk_insert(
        role_table,
        [
            {"slug": "unverified", "description": "Signed-up but no ID check"},
            {"slug": "id_verified", "description": "Doc verified, AML pending"},
            {"slug": "member", "description": "KYC/AML cleared"},
            {"slug": "member_wallet", "description": "Member with linked wallet"},
        ]
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_verification')
    # ### end Alembic commands ###
