"""add_fractional_listings

Revision ID: e15ca7c95a57
Revises: d84597c29117
Create Date: 2025-06-08 13:25:22.308508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15ca7c95a57'
down_revision: Union[str, None] = 'd84597c29117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fractional_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault', sa.String(), nullable=False),
    sa.Column('nft_contract', sa.String(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault', name='uq_fractional_vault')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fractional_listings')
    # ### end Alembic commands ###
