/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FractionalCollection } from "./FractionalCollection";
export type { FractionalShare } from "./FractionalShare";
